Allergy.find_or_create_by_name(name: "Alcohol",
                               snomed_name: "Alcohol products allergy",
                               snomed_code: "294420000",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Almond Oil",
                               snomed_name: "Allergy to almond oil",
                               snomed_code: "418606003",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Aluminum",
                               snomed_name: "Allergy to aluminum",
                               snomed_code: "402306009",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Ant Sting",
                               snomed_name: "Ant Sting",
                               snomed_code: "403141006",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Animal Dander",
                               snomed_name: "Dander (animal) allergy",
                               snomed_code: "232347008",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Aspartame",
                               snomed_name: "Allergy to aspartame",
                               snomed_code: "419180003",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Bee Sting",
                               snomed_name: "Allergy to bee venom",
                               snomed_code: "424213003",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Boric Acid",
                               snomed_name: "Boric acid allergy",
                               snomed_code: "294434000",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Caffeine",
                               snomed_name: "Caffeine allergy",
                               snomed_code: "418344001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Carrot",
                               snomed_name: "Carrot allergy",
                               snomed_code: "420080006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Castor Oil",
                               snomed_name: "Castor Oil allergy",
                               snomed_code: "294318004",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Cat Dander",
                               snomed_name: "Cat Dander allergy",
                               snomed_code: "232346004",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Cheese",
                               snomed_name: "Cheese allergy",
                               snomed_code: "300914000",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Chemical",
                               snomed_name: "Chemical allergy",
                               snomed_code: "419199007",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Chemicals",
                               snomed_name: "Chemical allergy",
                               snomed_code: "419199007",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Chocolate",
                               snomed_name: "Chocolate allergy",
                               snomed_code: "300912001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Clonidine",
                               snomed_name: "Clonidine allergy",
                               snomed_code: "294058006",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Cinnamon",
                               snomed_name: "Cinnamon allergy",
                               snomed_code: "418397007",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Coal Tar",
                               snomed_name: "Coal Tar allergy",
                               snomed_code: "294169006",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Coconut Oil",
                               snomed_name: "Coconut oil allergy",
                               snomed_code: "419814004",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Corn",
                               snomed_name: "Corn allergy",
                               snomed_code: "419573007",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Cosmetic",
                               snomed_name: "Cosmetic allergy",
                               snomed_code: "417982003",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Cow's milk",
                               snomed_name: "Cow's milk allergy",
                               snomed_code: "15911003",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Dairy",
                               snomed_name: "Dairy product allergy",
                               snomed_code: "425525006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Dander",
                               snomed_name: "Dander allergy",
                               snomed_code: "232347008",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Dog Dander",
                               snomed_name: "Dog Dander allergy",
                               snomed_code: "419271008",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Dust",
                               snomed_name: "Dust allergy",
                               snomed_code: "390952000",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Dye",
                               snomed_name: "Dye allergy",
                               snomed_code: "418545001",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Egg",
                               snomed_name: "Egg allergy",
                               snomed_code: "91930004",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Feather",
                               snomed_name: "Feather allergy",
                               snomed_code: "232348003",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Food",
                               snomed_name: "Food allergy",
                               snomed_code: "414285001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Food Preservative",
                               snomed_name: "Food preservative allergy",
                               snomed_code: "419421008",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Fruit",
                               snomed_name: "Fruit",
                               snomed_code: "91932007",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Gastrointestinal Food Allergy",
                               snomed_name: "Gastrointestinal food allergy",
                               snomed_code: "414314005",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Gauze",
                               snomed_name: "Gauze allergy",
                               snomed_code: "418968001",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Gelatin",
                               snomed_name: "Gelatin allergy",
                               snomed_code: "294847001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Glycine",
                               snomed_name: "Glycine allergy",
                               snomed_code: "294298002",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Gold",
                               snomed_name: "Gold allergy",
                               snomed_code: "294238000",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Grass Pollen",
                               snomed_name: "Grass pollen allergy",
                               snomed_code: "418689008",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Guar Gum",
                               snomed_name: "Guar gum allergy",
                               snomed_code: "294741005",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Gluten",
                               snomed_name: "Gluten allergy",
                               snomed_code: "2817841018",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Hornet Sting",
                               snomed_name: "Hornet sting",
                               snomed_code: "307427009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Horse Dander",
                               snomed_name: "Horse dander allergy",
                               snomed_code: "419063004",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "House Dust",
                               snomed_name: "House dust allergy",
                               snomed_code: "232349006",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Latex",
                               snomed_name: "Latex allergy",
                               snomed_code: "300916003",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Legumes",
                               snomed_name: "Legumes allergy",
                               snomed_code: "409136006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Lithium",
                               snomed_name: "Lithium allergy",
                               snomed_code: "293817009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Lubricant",
                               snomed_name: "Lubricant allergy",
                               snomed_code: "294321002",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Metal",
                               snomed_name: "Metal allergy",
                               snomed_code: "300915004",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Mold",
                               snomed_name: "Allergy to mold (disorder)",
                               snomed_code: "2575109010",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Multiple Environmental",
                               snomed_name: "Multiple environmental allergies",
                               snomed_code: "444026000",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Mushroom",
                               snomed_name: "Mushroom allergy",
                               snomed_code: "447961002",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Nickel",
                               snomed_name: "Nickel allergy",
                               snomed_code: "419788000",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "No Known Allergies",
                               snomed_name: "No Known Allergies",
                               snomed_code: "160244002",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "No Allergies",
                               snomed_name: "No Known Allergies",
                               snomed_code: "160244002",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "None",
                               snomed_name: "No Known Allergies",
                               snomed_code: "160244002",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Nut",
                               snomed_name: "Allergy to Nuts (Disorder)",
                               snomed_code: "835352016",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Nuts",
                               snomed_name: "Allergy to Nuts (Disorder)",
                               snomed_code: "835352016",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Oat",
                               snomed_name: "Oats allergy",
                               snomed_code: "419342009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Olive Oil",
                               snomed_name: "Olive oil allergy",
                               snomed_code: "294316000",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Other Allergy (Not Listed)",
                               snomed_name: "Other Allergy (Not Listed)",
                               snomed_code: "106190000",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Paraffin",
                               snomed_name: "Paraffin allergy",
                               snomed_code: "294324005",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Peanut",
                               snomed_name: "Allergy to Peanuts (Disorder)",
                               snomed_code: "835353014",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Peanuts",
                               snomed_name: "Allergy to Peanuts (Disorder)",
                               snomed_code: "835353014",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Pet Dander",
                               snomed_name: "Dander (animal) allergy",
                               snomed_code: "620400013",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Perfume",
                               snomed_name: "Perfume allergy",
                               snomed_code: "300908007",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Pesticide",
                               snomed_name: "Pesticide allergy",
                               snomed_code: "294619002",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Photosensitization",
                               snomed_name: "Photosensitization due to sun",
                               snomed_code: "258155009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Plant",
                               snomed_name: "Plant allergy",
                               snomed_code: "402594000",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Pollen",
                               snomed_name: "Pollen allergy",
                               snomed_code: "300910009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Pollen-Food",
                               snomed_name: "Pollen-food allergy",
                               snomed_code: "432807008",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Pork",
                               snomed_name: "Pork allergy",
                               snomed_code: "417918006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Potato",
                               snomed_name: "Potato allergy",
                               snomed_code: "419619007",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Red Meat",
                               snomed_name: "Red meat allergy",
                               snomed_code: "418815008",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Rubber",
                               snomed_name: "Rubber allergy",
                               snomed_code: "419412007",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Rye",
                               snomed_name: "Rye allergy",
                               snomed_code: "418184004",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Scorpion Sting",
                               snomed_name: "Scorpion sting",
                               snomed_code: "42292100",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Seafood",
                               snomed_name: "Seafood allergy",
                               snomed_code: "91937001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Seasonal",
                               snomed_name: "Seasonal allergy",
                               snomed_code: "444316004",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Seed",
                               snomed_name: "Seed allergy",
                               snomed_code: "419101002",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Shellfish",
                               snomed_name: "Shellfish allergy",
                               snomed_code: "300913006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Shrimp",
                               snomed_name: "Shrimp allergy",
                               snomed_code: "419972009",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Silicone",
                               snomed_name: "Silicone allergy",
                               snomed_code: "294328008",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Spider Bite",
                               snomed_name: "Spider bite allergy",
                               snomed_code: "427487000",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Strawberry",
                               snomed_name: "Allergy to Strawberries (Disorder)",
                               snomed_code: "91938006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Strawberries",
                               snomed_name: "Allergy to Strawberries (Disorder)",
                               snomed_code: "91938006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Soy",
                               snomed_name: "Soy protein sensitivity (disorder)",
                               snomed_code: "756234018",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Sulfur",
                               snomed_name: "Sulfur allergy",
                               snomed_code: "294179008",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Sunlight",
                               snomed_name: "Photosensitization due to sun",
                               snomed_code: "258155009",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Tape",
                               snomed_name: "Tape allergy",
                               snomed_code: "405649006",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Tomato",
                               snomed_name: "Tomato allergy",
                               snomed_code: "418779002",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Tryptophan",
                               snomed_name: "Tryptophan allergy",
                               snomed_code: "293842000",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Vitamin A",
                               snomed_name: "Vitamin A allergy",
                               snomed_code: "294923007",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Vitamin D",
                               snomed_name: "Vitamin D allergy",
                               snomed_code: "294924001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Vitamin K",
                               snomed_name: "Vitamin K allergy",
                               snomed_code: "294925000",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Walnut",
                               snomed_name: "Walnut allergy",
                               snomed_code: "91940001",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Wasp Sting",
                               snomed_name: "Wasp sting allergy",
                               snomed_code: "423058007",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Wheat",
                               snomed_name: "Wheat allergy",
                               snomed_code: "402595004",
                               food_allergen: "true",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Wool",
                               snomed_name: "Wool allergy",
                               snomed_code: "425605001",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Zinc",
                               snomed_name: "Zinc allergy",
                               snomed_code: "294950002",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Penicillin",
                               snomed_name: "Allergy to penicillin (disorder)",
                               snomed_code: "835354015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Insulin",
                               snomed_name: "Insulin allergy (disorder)",
                               snomed_code: "689744011",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Sulfonamides",
                               snomed_name: "Allergy to sulfonamides (disorder)",
                               snomed_code: "689744011",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Sulfa drugs",
                               snomed_name: "Allergy to sulfa drugs",
                               snomed_code: "152311016",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Nifedipine",
                               snomed_name: "Nifedipine allergy ",
                               snomed_code: "688948011",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Cephalosporin",
                               snomed_name: "Cephalosporin allergy (disorder)",
                               snomed_code: "689542012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Lorabid",
                               snomed_name: "Cephalosporin allergy (disorder)",
                               snomed_code: "689542012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Loracarbef",
                               snomed_name: "Cephalosporin allergy (disorder)",
                               snomed_code: "689542012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Morphine",
                               snomed_name: "Morphine allergy (disorder)",
                               snomed_code: "688509015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Codeine",
                               snomed_name: "Codeine allergy (disorder)",
                               snomed_code: "688505014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Dust mites",
                               snomed_name: "House dust mite allergy (disorder)",
                               snomed_code: "620404016",
                               food_allergen: "false",
                               environment_allergen: "true",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Red Meat",
                               snomed_name: "Allergy to red meat (disorder)",
                               snomed_code: "2575113015",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Beef",
                               snomed_name: "Allergy to red meat (disorder)",
                               snomed_code: "2575113015",
                               food_allergen: "true",
                               environment_allergen: "false",
                               medication_allergen: "false")
Allergy.find_or_create_by_name(name: "Simvastatin",
                               snomed_name: "Simvastatin allergy (disorder)",
                               snomed_code: "2575113015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Simvastatin",
                               snomed_name: "Simvastatin allergy (disorder)",
                               snomed_code: "2575113015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Omeprazole",
                               snomed_name: "Omeprazole allergy (disorder)",
                               snomed_code: "688570017",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Vancomycin",
                               snomed_name: "Vancomycin allergy (disorder)",
                               snomed_code: "689480010",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Azathioprine",
                               snomed_name: "Azathioprine allergy (disorder)",
                               snomed_code: "688729016",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Phenobarbitone",
                               snomed_name: "Phenobarbitone allergy (disorder)",
                               snomed_code: "688802015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Phenobarbital",
                               snomed_name: "Phenobarbitone allergy (disorder)",
                               snomed_code: "2476289015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Phenobarbital",
                               snomed_name: "Phenobarbitone allergy (disorder)",
                               snomed_code: "2476289015",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Codeine",
                               snomed_name: "Codeine allergy (disorder)",
                               snomed_code: "293597001",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Aspirin",
                               snomed_name: "Aspirin allergy (disorder)",
                               snomed_code: "688493014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Ibuprofen",
                               snomed_name: "Ibuprofen allergy (disorder)",
                               snomed_code: "688529019",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Tetracycline",
                               snomed_name: "Tetracycline allergy (disorder)",
                               snomed_code: "689609017",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Tetracycline",
                               snomed_name: "Tetracycline allergy (disorder)",
                               snomed_code: "689609017",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Dopamine",
                               snomed_name: "Dopamine allergy (disorder)",
                               snomed_code: "294061007",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Ephedrine",
                               snomed_name: "Ephedrine allergy (disorder)",
                               snomed_code: "689022014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Amoxicillin",
                               snomed_name: "Amoxicillin allergy (disorder)",
                               snomed_code: "2959758014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Sulfonamides",
                               snomed_name: "Allergy to sulfonamides (disorder)",
                               snomed_code: "835357010",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Zonisamide",
                               snomed_name: "Allergy to sulfonamides (disorder)",
                               snomed_code: "835357010",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Codeine",
                               snomed_name: "Codeine allergy (disorder)",
                               snomed_code: "688505014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Omnicef",
                               snomed_name: "Cephalosporin allergy (disorder)",
                               snomed_code: "689542012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Cephalosporin",
                               snomed_name: "Cephalosporin allergy (disorder)",
                               snomed_code: "689542012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Sertraline",
                               snomed_name: "Sertraline allergy (disorder)",
                               snomed_code: "688779018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Zoloft",
                               snomed_name: "Sertraline allergy (disorder)",
                               snomed_code: "688779018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Phenytoin",
                               snomed_name: "Phenytoin allergy (disorder)",
                               snomed_code: "688807014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Dilantin",
                               snomed_name: "Phenytoin allergy (disorder)",
                               snomed_code: "688807014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Tegratol",
                               snomed_name: "Carbamazepine allergy (disorder)",
                               snomed_code: "688805018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Carbamazepine",
                               snomed_name: "Carbamazepine allergy (disorder)",
                               snomed_code: "688805018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Metoclopramide",
                               snomed_name: "Metoclopramide allergy (disorder)",
                               snomed_code: "688592018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Reglan",
                               snomed_name: "Metoclopramide allergy (disorder)",
                               snomed_code: "688592018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Amiodarone",
                               snomed_name: "Amiodarone allergy (disorder)",
                               snomed_code: "690049018",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Azathioprine",
                               snomed_name: "Azathioprine allergy (disorder)",
                               snomed_code: "688729016",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Imuran",
                               snomed_name: "Azathioprine allergy (disorder)",
                               snomed_code: "688729016",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Azasan",
                               snomed_name: "Azathioprine allergy (disorder)",
                               snomed_code: "688729016",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Primidone",
                               snomed_name: "Primidone allergy (disorder)",
                               snomed_code: "688803013",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Mycoline",
                               snomed_name: "Primidone allergy (disorder)",
                               snomed_code: "688803013",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Tramadol",
                               snomed_name: "Allergy to tramadol (disorder)",
                               snomed_code: "2916926012",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
Allergy.find_or_create_by_name(name: "Povidone Iodine",
                               snomed_name: "Povidone iodine allergy (disorder)",
                               snomed_code: "689968014",
                               food_allergen: "false",
                               environment_allergen: "false",
                               medication_allergen: "true")
