language: ruby
cache: bundler
rvm:
  - 2.0.0-p598
before_script:
  - mv config/application.yml.example config/application.yml
  - mv config/database.yml.example config/database.yml
  - mysql -e 'create database rhs_test;'
  - mysql -e 'create database rhs_test2;'
script: "true"
after_success:
  - [[ $TRAVIS_BRANCH = 'develop' ]] && bundle exec cap devhosted deploy
