language: ruby
cache: bundler
rvm:
  - 2.0.0-p598
before_script:
  - mv config/application.yml.example config/application.yml
  - mv config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake parallel:create parallel:load_schema
script: "RAILS_ENV=test bundle exec parallel_rspec spec"
