language: ruby
cache: bundler
rvm:
  - 2.0.0-p598
before_script:
  - mv config/application.yml.example config/application.yml
  - mv config/database.yml.example config/database.yml
  - mysql -e 'create database rhs_test;'
  - mysql -e 'create database rhs_test2;'
script: "true"
after_success:
  - ssh -p 9722 rhs@goldenbear.getbetter.com -o 'StrictHostKeyChecking=no' -o 'BatchMode=yes' -o 'ConnectionAttempts=1' -o 'ConnectTimeout=2' echo "Connected to Goldenbear"
  - cap devhosted deploy
