default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rhs_development
  username: rhs_development
  password: password
  host: localhost

test:
  <<: *default
  database: rhs_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: rhs_test
  password: password
  host: localhost
  min_messages: WARNING

# production:
#   adapter: pg
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
