class AddIndexOnForeignKeys < ActiveRecord::Migration
  def change
    add_index :addresses, :user_id
    add_index :appointments, :user_id
    add_index :associations, :associate_id
    add_index :associations, :association_type_id
    add_index :associations, :creator_id
    add_index :associations, :replacement_id
    add_index :communication_workflow_templates, :communication_workflow_id,
              :name => "index_communication_workflow_id"
    add_index :consults, :initiator_id
    add_index :consults, :symptom_id
    add_index :consults, :subject_id
    add_index :content_mayo_vocabularies, :content_id
    add_index :content_mayo_vocabularies, :mayo_vocabulary_id
    add_index :content_references, :referee_id
    add_index :content_references, :referrer_id
    add_index :contents, :condition_id
    add_index :custom_cards, :content_id
    add_index :discounts, :user_id
    add_index :discounts, :referral_code_id
    add_index :emergency_contacts, :user_id
    add_index :emergency_contacts, :designee_id
    add_index :factor_contents, :factor_id
    add_index :factor_contents, :content_id
    add_index :factors, :factor_group_id
    add_index :heights, :user_id
    add_index :heights, :creator_id
    add_index :insurance_policies, :user_id
    add_index :insurance_policies, :insurance_card_back_id
    add_index :insurance_policies, :insurance_card_front_id
    add_index :invitations, :member_id
    add_index :member_state_transitions, :actor_id
    add_index :message_templates, :content_id
    add_index :nurseline_records, :api_user_id
    add_index :nux_story_changes, :nux_story_id
    add_index :onboarding_group_cards, [:onboarding_group_id, :resource_id],
              :name => "index_onboarding_group_id_resource_id"
    add_index :onboarding_group_programs, :onboarding_group_id
    add_index :onboarding_group_programs, :program_id
    add_index :onboarding_groups, :provider_id
    add_index :onboarding_groups, :trial_nux_story_id
    add_index :onboarding_groups, :pha_id
    add_index :parsed_nurseline_records, :user_id
    add_index :parsed_nurseline_records, :consult_id
    add_index :parsed_nurseline_records, :phone_call_id
    add_index :parsed_nurseline_records, :nurseline_record_id
    add_index :pha_profiles, :user_id
    add_index :pha_profiles, :nux_answer_id
    add_index :phone_call_summaries, :callee_id
    add_index :phone_call_summaries, :caller_id
    add_index :program_resources, [:program_id, :resource_id], :name => "index_program_id_resource_id_on_program_resources"
    add_index :providers, :user_id
    add_index :referral_codes, :creator_id
    add_index :referral_codes, :user_id
    add_index :remote_events, :user_id
    add_index :service_state_transitions, :actor_id
    add_index :service_templates, :service_type_id
    add_index :services, :member_id
    add_index :services, :service_type_id
    add_index :services, :creator_id
    add_index :services, :assignor_id
    add_index :services, :subject_id
    add_index :subscription_users, :subscription_id
    add_index :task_guides, :task_template_id
    add_index :task_requirement_templates, :task_template_id
    add_index :task_requirements, :task_requirement_template_id
    add_index :task_templates, :service_template_id
    add_index :treatment_side_effects, :treatment_id
    add_index :user_changes, :user_id
    add_index :user_changes, :actor_id
    add_index :user_condition_user_treatments, :user_condition_id
    add_index :user_condition_user_treatments, :user_treatment_id
    add_index :user_conditions, :user_id
    add_index :user_conditions, :condition_id
    add_index :user_conditions, :diagnoser_id
    add_index :user_content_likes, :user_id
    add_index :user_content_likes, :content_id
    add_index :user_feature_groups, :user_id
    add_index :user_feature_groups, :feature_group_id
    add_index :user_images, :user_id
    add_index :user_informations, :user_id
    add_index :user_programs, :user_id
    add_index :user_programs, :program_id
    add_index :user_programs, :subject_id
    add_index :user_request_type_fields, :user_request_type_id
    add_index :user_requests, :user_id
    add_index :user_requests, :subject_id
    add_index :user_requests, :user_request_type_id
    add_index :user_roles, :user_id
    add_index :user_roles, :role_id
    add_index :user_treatment_side_effects, :user_treatment_id
    add_index :user_treatment_side_effects, :side_effect_id
    add_index :user_treatments, :treatment_id
    add_index :user_treatments, :user_id
    add_index :user_treatments, :doctor_id
    add_index :weights, :user_id
    add_index :weights, :creator_id
  end
end


